# Generated by Django 3.1.3 on 2020-11-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsystem', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='НАЗВАНИЕ', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='ОПИСАНИЕ', max_length=255, verbose_name='Описание')),
                ('salary', models.CharField(blank=True, max_length=255, verbose_name='Заработная плата')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.company', verbose_name='Что за компания')),
                ('tags', models.ManyToManyField(blank=True, to='vacancy.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='users_vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate', verbose_name='Какой юзер')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy', verbose_name='Вакансия юзера')),
            ],
        ),
    ]
