# Generated by Django 3.1.3 on 2020-11-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, to='authsystem.Candidate', verbose_name='Кандидаты'),
        ),
    ]
