# Generated by Django 3.1.3 on 2020-11-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.CharField(default='ОПИСАНИЕ', max_length=255, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default='НАЗВАНИЕ', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заработная плата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(blank=True, to='vacancy.Tag', verbose_name='Теги'),
        ),
    ]
