# Generated by Django 3.1.3 on 2020-11-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsystem', '0001_initial'),
        ('vacancy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy', verbose_name='Вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quest', models.TextField(verbose_name='Вопрос')),
                ('type', models.IntegerField(default=0, verbose_name='Тип вопроса')),
                ('jsn_ans', models.TextField(verbose_name='Варианты ответа')),
                ('jsn_is_true', models.TextField(verbose_name='Какие варианты ответа верны?')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ans', models.TextField(verbose_name='Ответы пользователя')),
                ('accuracy', models.IntegerField(verbose_name='Процент верных ответов')),
                ('order', models.IntegerField(verbose_name='порядок')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate', verbose_name='Соискатель')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy', verbose_name='Вакансия')),
            ],
        ),
    ]
