# Generated by Django 3.1.3 on 2020-11-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_auto_20201106_0809'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='quest',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='id_test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Вопросы'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ResultsTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate', verbose_name='Соискатель')),
            ],
        ),
    ]
