# Generated by Django 3.1.3 on 2020-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultstest',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='testquestion',
            name='img',
            field=models.FileField(blank=True, upload_to='tests/media/', verbose_name='Картинка'),
        ),
    ]
