# Generated by Django 3.1.3 on 2020-11-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultstest',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты теста'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'verbose_name': 'Вопрос к тесту', 'verbose_name_plural': 'Вопросы к тесту'},
        ),
    ]
