# Generated by Django 3.1.3 on 2020-11-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
        ('tests', '0002_auto_20201106_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultstest',
            name='accuracy',
            field=models.IntegerField(default=90, verbose_name='Процент верных ответов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultstest',
            name='ans',
            field=models.TextField(default=1, verbose_name='Ответы пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultstest',
            name='id_test',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultstest',
            name='order',
            field=models.IntegerField(default=2, verbose_name='порядок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultstest',
            name='vacancy',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy', verbose_name='Вакансия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
    ]
