# Generated by Django 3.1.3 on 2020-11-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20201107_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='img',
            field=models.ImageField(blank=True, upload_to='tests/media/', verbose_name='Картинка'),
        ),
    ]
