# Generated by Django 3.1.3 on 2020-11-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20201107_2216'),
        ('tests', '0002_auto_20201107_1935'),
    ]

    operations = [
    ]
