# Generated by Django 3.1.3 on 2020-11-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20201106_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultstest',
            old_name='condidate',
            new_name='candidate',
        ),
    ]
