# Generated by Django 3.1.3 on 2020-11-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_merge_20201107_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultstest',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='img',
            field=models.ImageField(blank=True, upload_to='tests/static/media/', verbose_name='Картинка'),
        ),
    ]
