# Generated by Django 3.1.3 on 2020-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='stage',
            field=models.IntegerField(default=1, verbose_name='Номер стадии'),
        ),
    ]
