# Generated by Django 3.1.3 on 2020-11-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Тексты'},
        ),
    ]
