# Generated by Django 3.1.3 on 2020-11-06 07:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('addition_contacts', models.TextField(verbose_name='Дополнительная контактная информация')),
                ('description', models.TextField(verbose_name='О себе')),
                ('cv', models.FileField(upload_to='', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('position', models.CharField(max_length=255, verbose_name='Название должности')),
                ('description', models.TextField(verbose_name='Обязанности')),
                ('date', models.DurationField(verbose_name='Период работы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate', verbose_name='Чье')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название учебного заведения')),
                ('description', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('date_finish', models.IntegerField(verbose_name='Год окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate', verbose_name='Чье')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='tags',
            field=models.ManyToManyField(to='authsystem.Tag'),
        ),
    ]
