# Generated by Django 3.1.3 on 2020-11-07 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('addition_contacts', models.TextField(verbose_name='Дополнительная контактная информация')),
                ('description', models.TextField(verbose_name='О себе')),
                ('cv', models.FileField(upload_to='', verbose_name='Резюме')),
                ('is_company', models.BooleanField(default=False, verbose_name='Это компания?')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('position', models.CharField(max_length=255, verbose_name='Название должности')),
                ('description', models.TextField(verbose_name='Обязанности')),
                ('date', models.DurationField(verbose_name='Период работы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate', verbose_name='Чье')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название учебного заведения')),
                ('description', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('date_finish', models.IntegerField(verbose_name='Год окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate', verbose_name='Чье')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('FIO_CEO', models.CharField(max_length=255, verbose_name='ФИО Директора')),
                ('Phone_CEO', models.CharField(max_length=12, verbose_name='Телефон Директора')),
                ('Email_CEO', models.CharField(max_length=100, verbose_name='Почта Директора')),
                ('FIO_Contact', models.CharField(max_length=255, verbose_name='ФИО Конатктного лица')),
                ('Phone_Contact', models.CharField(max_length=12, verbose_name='Телефон Конактного лица')),
                ('Email_Contact', models.CharField(max_length=12, verbose_name='Почта Конатктного лица')),
                ('description', models.TextField(verbose_name='О компании')),
                ('img_logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип компании')),
                ('place', models.CharField(max_length=300, verbose_name='Адрес компании')),
                ('is_company', models.BooleanField(default=True, verbose_name='Это компания?')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
            },
        ),
    ]
