# Generated by Django 3.1.3 on 2020-11-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Соискатель', 'verbose_name_plural': 'Соискатели'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Работодатель', 'verbose_name_plural': 'Работодатели'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Это компания?'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_company',
            field=models.BooleanField(default=True, verbose_name='Это компания?'),
        ),
    ]
