# Generated by Django 3.1.3 on 2020-11-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_auto_20201106_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
