# Generated by Django 3.1.3 on 2020-11-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0004_auto_20201106_1428'),
        ('authsystem', '0003_company_user'),
    ]

    operations = [
    ]
