# Generated by Django 3.1.3 on 2020-11-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsystem', '0001_initial'),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='Порядковый номер')),
                ('description', models.TextField(verbose_name='Текст задания')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy', verbose_name='Какой вакансии')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='OpenFormAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Ответ на вопрос')),
                ('answer_file', models.FileField(blank=True, upload_to='media/', verbose_name='Прикрепленный файл')),
                ('mark', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate')),
                ('open_form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_form.openform')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
