# Generated by Django 3.1.3 on 2020-11-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openform',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='openformanswer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
