# Generated by Django 3.1.3 on 2020-11-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openformanswer',
            name='mark',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
