# Generated by Django 3.1.3 on 2020-11-07 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '__first__'),
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядковый номер этапа')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Очное собеседование',
                'verbose_name_plural': 'Очные собеседования',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('order', models.IntegerField(verbose_name='Номер вопроса')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview', verbose_name='Интервью')),
            ],
            options={
                'verbose_name': 'Вопрос собеседования',
                'verbose_name_plural': 'Вопросы собеседования',
            },
        ),
        migrations.CreateModel(
            name='InterviewTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='тэг для быстрого ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewquestion', verbose_name='Вопрос тэга')),
            ],
            options={
                'verbose_name': 'Тэг вопроса собеседования',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(verbose_name='Результат')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewquestion', verbose_name='Вопрос тэга')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate', verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
