# Generated by Django 3.1.3 on 2020-11-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '0001_initial'),
        ('authsystem', '0003_auto_20201106_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='Порядковый номер этапа')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy', verbose_name='Вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('order', models.IntegerField(verbose_name='Номер вопроса')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview', verbose_name='Интервью')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='тэг для быстрого ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewquestion', verbose_name='Вопрос тэга')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(verbose_name='Результат')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewquestion', verbose_name='Вопрос тэга')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.candidate', verbose_name='Соискатель')),
            ],
        ),
    ]
