# Generated by Django 3.1.3 on 2020-11-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Очное собеседование', 'verbose_name_plural': 'Очные собеседования'},
        ),
        migrations.AlterModelOptions(
            name='interviewanswer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'verbose_name': 'Вопрос собеседования', 'verbose_name_plural': 'Вопросы собеседования'},
        ),
        migrations.AlterModelOptions(
            name='interviewtags',
            options={'verbose_name': 'Тэг вопроса собеседования', 'verbose_name_plural': 'Теги'},
        ),
    ]
